apiVersion: v1
kind: Service
metadata:
  labels:
    app: another-thing-prod
  name: another-thing-prod
  namespace: another-thing
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: another-thing-prod
