apiVersion: v1
kind: Service
metadata:
  name: vcluster-hkg
  namespace: vcluster-hkg
spec:
  selector:
    app: vcluster
    release: hkg
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort
