apiVersion: v1
kind: Service
metadata:
  name: vcluster-sin
  namespace: vcluster-sin
spec:
  selector:
    app: vcluster
    release: sin
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort
