apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: another-thing-prod-cgk
  namespace: argocd
spec:
  project: default
  source:
    path: prod/another-thing-prod
    repoURL: https://github.com/faultables/animated-winner
  destination:
    name: cgk
    namespace: another-thing

