apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: another-thing-prod-hkg
  namespace: argocd
spec:
  project: default
  source:
    path: prod/another-thing-prod
    repoURL: https://github.com/faultables/animated-winner
  destination:
    name: hkg
    namespace: another-thing
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
