apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: something-prod-hkg
  namespace: argocd
spec:
  project: default
  source:
    path: prod/something-prod
    repoURL: https://github.com/faultables/animated-winner
  destination:
    name: hkg
    namespace: something
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
